name: which

on:
  push:
    branches: [ "i01" ]
  pull_request:
    branches: [ "i01" ]

jobs:
  which-reality:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Startup web server
    - name: Copy .env
      run: docker run -v $(pwd):/var/www/html -dit --rm --name php php:apache
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.3.0
      with:
         target: http://172.17.0.2
